--
-- Julien Moquet. Licence Cecill v2. Février 2011.
--
-- Permet de créer les index utiles à JDONREFv2 concernant les points adresse.
-- A noter que d'autres index peuvent être mis en place pour optimiser la mise à jour du référentiel.
--
-- L'extension postgis doit être présente (index GIST)

-- point adresse
CREATE INDEX adr_adresses_01_voi_id_numero_rep ON adr_adresses_01 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_01_geometrie ON adr_adresses_01 USING gist (geometrie);
CREATE INDEX adr_adresses_02_voi_id_numero_rep ON adr_adresses_02 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_02_geometrie ON adr_adresses_02 USING gist (geometrie);
CREATE INDEX adr_adresses_03_voi_id_numero_rep ON adr_adresses_03 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_03_geometrie ON adr_adresses_03 USING gist (geometrie);
CREATE INDEX adr_adresses_04_voi_id_numero_rep ON adr_adresses_04 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_04_geometrie ON adr_adresses_04 USING gist (geometrie);
CREATE INDEX adr_adresses_05_voi_id_numero_rep ON adr_adresses_05 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_05_geometrie ON adr_adresses_05 USING gist (geometrie);
CREATE INDEX adr_adresses_06_voi_id_numero_rep ON adr_adresses_06 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_06_geometrie ON adr_adresses_06 USING gist (geometrie);
CREATE INDEX adr_adresses_07_voi_id_numero_rep ON adr_adresses_07 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_07_geometrie ON adr_adresses_07 USING gist (geometrie);
CREATE INDEX adr_adresses_08_voi_id_numero_rep ON adr_adresses_08 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_08_geometrie ON adr_adresses_08 USING gist (geometrie);
CREATE INDEX adr_adresses_09_voi_id_numero_rep ON adr_adresses_09 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_09_geometrie ON adr_adresses_09 USING gist (geometrie);
CREATE INDEX adr_adresses_10_voi_id_numero_rep ON adr_adresses_10 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_10_geometrie ON adr_adresses_10 USING gist (geometrie);
CREATE INDEX adr_adresses_11_voi_id_numero_rep ON adr_adresses_11 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_11_geometrie ON adr_adresses_11 USING gist (geometrie);
CREATE INDEX adr_adresses_12_voi_id_numero_rep ON adr_adresses_12 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_12_geometrie ON adr_adresses_12 USING gist (geometrie);
CREATE INDEX adr_adresses_13_voi_id_numero_rep ON adr_adresses_13 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_13_geometrie ON adr_adresses_13 USING gist (geometrie);
CREATE INDEX adr_adresses_14_voi_id_numero_rep ON adr_adresses_14 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_14_geometrie ON adr_adresses_14 USING gist (geometrie);
CREATE INDEX adr_adresses_15_voi_id_numero_rep ON adr_adresses_15 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_15_geometrie ON adr_adresses_15 USING gist (geometrie);
CREATE INDEX adr_adresses_16_voi_id_numero_rep ON adr_adresses_16 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_16_geometrie ON adr_adresses_16 USING gist (geometrie);
CREATE INDEX adr_adresses_17_voi_id_numero_rep ON adr_adresses_17 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_17_geometrie ON adr_adresses_17 USING gist (geometrie);
CREATE INDEX adr_adresses_18_voi_id_numero_rep ON adr_adresses_18 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_18_geometrie ON adr_adresses_18 USING gist (geometrie);
CREATE INDEX adr_adresses_19_voi_id_numero_rep ON adr_adresses_19 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_19_geometrie ON adr_adresses_19 USING gist (geometrie);
CREATE INDEX adr_adresses_21_voi_id_numero_rep ON adr_adresses_21 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_21_geometrie ON adr_adresses_21 USING gist (geometrie);
CREATE INDEX adr_adresses_22_voi_id_numero_rep ON adr_adresses_22 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_22_geometrie ON adr_adresses_22 USING gist (geometrie);
CREATE INDEX adr_adresses_23_voi_id_numero_rep ON adr_adresses_23 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_23_geometrie ON adr_adresses_23 USING gist (geometrie);
CREATE INDEX adr_adresses_24_voi_id_numero_rep ON adr_adresses_24 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_24_geometrie ON adr_adresses_24 USING gist (geometrie);
CREATE INDEX adr_adresses_25_voi_id_numero_rep ON adr_adresses_25 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_25_geometrie ON adr_adresses_25 USING gist (geometrie);
CREATE INDEX adr_adresses_26_voi_id_numero_rep ON adr_adresses_26 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_26_geometrie ON adr_adresses_26 USING gist (geometrie);
CREATE INDEX adr_adresses_27_voi_id_numero_rep ON adr_adresses_27 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_27_geometrie ON adr_adresses_27 USING gist (geometrie);
CREATE INDEX adr_adresses_28_voi_id_numero_rep ON adr_adresses_28 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_28_geometrie ON adr_adresses_28 USING gist (geometrie);
CREATE INDEX adr_adresses_29_voi_id_numero_rep ON adr_adresses_29 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_29_geometrie ON adr_adresses_29 USING gist (geometrie);
CREATE INDEX adr_adresses_30_voi_id_numero_rep ON adr_adresses_30 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_30_geometrie ON adr_adresses_30 USING gist (geometrie);
CREATE INDEX adr_adresses_31_voi_id_numero_rep ON adr_adresses_31 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_31_geometrie ON adr_adresses_31 USING gist (geometrie);
CREATE INDEX adr_adresses_32_voi_id_numero_rep ON adr_adresses_32 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_32_geometrie ON adr_adresses_32 USING gist (geometrie);
CREATE INDEX adr_adresses_33_voi_id_numero_rep ON adr_adresses_33 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_33_geometrie ON adr_adresses_33 USING gist (geometrie);
CREATE INDEX adr_adresses_34_voi_id_numero_rep ON adr_adresses_34 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_34_geometrie ON adr_adresses_34 USING gist (geometrie);
CREATE INDEX adr_adresses_35_voi_id_numero_rep ON adr_adresses_35 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_35_geometrie ON adr_adresses_35 USING gist (geometrie);
CREATE INDEX adr_adresses_36_voi_id_numero_rep ON adr_adresses_36 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_36_geometrie ON adr_adresses_36 USING gist (geometrie);
CREATE INDEX adr_adresses_37_voi_id_numero_rep ON adr_adresses_37 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_37_geometrie ON adr_adresses_37 USING gist (geometrie);
CREATE INDEX adr_adresses_38_voi_id_numero_rep ON adr_adresses_38 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_38_geometrie ON adr_adresses_38 USING gist (geometrie);
CREATE INDEX adr_adresses_39_voi_id_numero_rep ON adr_adresses_39 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_39_geometrie ON adr_adresses_39 USING gist (geometrie);
CREATE INDEX adr_adresses_40_voi_id_numero_rep ON adr_adresses_40 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_40_geometrie ON adr_adresses_40 USING gist (geometrie);
CREATE INDEX adr_adresses_41_voi_id_numero_rep ON adr_adresses_41 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_41_geometrie ON adr_adresses_41 USING gist (geometrie);
CREATE INDEX adr_adresses_42_voi_id_numero_rep ON adr_adresses_42 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_42_geometrie ON adr_adresses_42 USING gist (geometrie);
CREATE INDEX adr_adresses_43_voi_id_numero_rep ON adr_adresses_43 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_43_geometrie ON adr_adresses_43 USING gist (geometrie);
CREATE INDEX adr_adresses_44_voi_id_numero_rep ON adr_adresses_44 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_44_geometrie ON adr_adresses_44 USING gist (geometrie);
CREATE INDEX adr_adresses_45_voi_id_numero_rep ON adr_adresses_45 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_45_geometrie ON adr_adresses_45 USING gist (geometrie);
CREATE INDEX adr_adresses_46_voi_id_numero_rep ON adr_adresses_46 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_46_geometrie ON adr_adresses_46 USING gist (geometrie);
CREATE INDEX adr_adresses_47_voi_id_numero_rep ON adr_adresses_47 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_47_geometrie ON adr_adresses_47 USING gist (geometrie);
CREATE INDEX adr_adresses_48_voi_id_numero_rep ON adr_adresses_48 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_48_geometrie ON adr_adresses_48 USING gist (geometrie);
CREATE INDEX adr_adresses_49_voi_id_numero_rep ON adr_adresses_49 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_49_geometrie ON adr_adresses_49 USING gist (geometrie);
CREATE INDEX adr_adresses_50_voi_id_numero_rep ON adr_adresses_50 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_50_geometrie ON adr_adresses_50 USING gist (geometrie);
CREATE INDEX adr_adresses_51_voi_id_numero_rep ON adr_adresses_51 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_51_geometrie ON adr_adresses_51 USING gist (geometrie);
CREATE INDEX adr_adresses_52_voi_id_numero_rep ON adr_adresses_52 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_52_geometrie ON adr_adresses_52 USING gist (geometrie);
CREATE INDEX adr_adresses_53_voi_id_numero_rep ON adr_adresses_53 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_53_geometrie ON adr_adresses_53 USING gist (geometrie);
CREATE INDEX adr_adresses_54_voi_id_numero_rep ON adr_adresses_54 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_54_geometrie ON adr_adresses_54 USING gist (geometrie);
CREATE INDEX adr_adresses_55_voi_id_numero_rep ON adr_adresses_55 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_55_geometrie ON adr_adresses_55 USING gist (geometrie);
CREATE INDEX adr_adresses_56_voi_id_numero_rep ON adr_adresses_56 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_56_geometrie ON adr_adresses_56 USING gist (geometrie);
CREATE INDEX adr_adresses_57_voi_id_numero_rep ON adr_adresses_57 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_57_geometrie ON adr_adresses_57 USING gist (geometrie);
CREATE INDEX adr_adresses_58_voi_id_numero_rep ON adr_adresses_58 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_58_geometrie ON adr_adresses_58 USING gist (geometrie);
CREATE INDEX adr_adresses_59_voi_id_numero_rep ON adr_adresses_59 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_59_geometrie ON adr_adresses_59 USING gist (geometrie);
CREATE INDEX adr_adresses_60_voi_id_numero_rep ON adr_adresses_60 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_60_geometrie ON adr_adresses_60 USING gist (geometrie);
CREATE INDEX adr_adresses_61_voi_id_numero_rep ON adr_adresses_61 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_61_geometrie ON adr_adresses_61 USING gist (geometrie);
CREATE INDEX adr_adresses_62_voi_id_numero_rep ON adr_adresses_62 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_62_geometrie ON adr_adresses_62 USING gist (geometrie);
CREATE INDEX adr_adresses_63_voi_id_numero_rep ON adr_adresses_63 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_63_geometrie ON adr_adresses_63 USING gist (geometrie);
CREATE INDEX adr_adresses_64_voi_id_numero_rep ON adr_adresses_64 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_64_geometrie ON adr_adresses_64 USING gist (geometrie);
CREATE INDEX adr_adresses_65_voi_id_numero_rep ON adr_adresses_65 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_65_geometrie ON adr_adresses_65 USING gist (geometrie);
CREATE INDEX adr_adresses_66_voi_id_numero_rep ON adr_adresses_66 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_66_geometrie ON adr_adresses_66 USING gist (geometrie);
CREATE INDEX adr_adresses_67_voi_id_numero_rep ON adr_adresses_67 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_67_geometrie ON adr_adresses_67 USING gist (geometrie);
CREATE INDEX adr_adresses_68_voi_id_numero_rep ON adr_adresses_68 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_68_geometrie ON adr_adresses_68 USING gist (geometrie);
CREATE INDEX adr_adresses_69_voi_id_numero_rep ON adr_adresses_69 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_69_geometrie ON adr_adresses_69 USING gist (geometrie);
CREATE INDEX adr_adresses_70_voi_id_numero_rep ON adr_adresses_70 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_70_geometrie ON adr_adresses_70 USING gist (geometrie);
CREATE INDEX adr_adresses_71_voi_id_numero_rep ON adr_adresses_71 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_71_geometrie ON adr_adresses_71 USING gist (geometrie);
CREATE INDEX adr_adresses_72_voi_id_numero_rep ON adr_adresses_72 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_72_geometrie ON adr_adresses_72 USING gist (geometrie);
CREATE INDEX adr_adresses_73_voi_id_numero_rep ON adr_adresses_73 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_73_geometrie ON adr_adresses_73 USING gist (geometrie);
CREATE INDEX adr_adresses_74_voi_id_numero_rep ON adr_adresses_74 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_74_geometrie ON adr_adresses_74 USING gist (geometrie);
CREATE INDEX adr_adresses_75_voi_id_numero_rep ON adr_adresses_75 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_75_geometrie ON adr_adresses_75 USING gist (geometrie);
CREATE INDEX adr_adresses_76_voi_id_numero_rep ON adr_adresses_76 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_76_geometrie ON adr_adresses_76 USING gist (geometrie);
CREATE INDEX adr_adresses_77_voi_id_numero_rep ON adr_adresses_77 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_77_geometrie ON adr_adresses_77 USING gist (geometrie);
CREATE INDEX adr_adresses_78_voi_id_numero_rep ON adr_adresses_78 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_78_geometrie ON adr_adresses_78 USING gist (geometrie);
CREATE INDEX adr_adresses_79_voi_id_numero_rep ON adr_adresses_79 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_79_geometrie ON adr_adresses_79 USING gist (geometrie);
CREATE INDEX adr_adresses_80_voi_id_numero_rep ON adr_adresses_80 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_80_geometrie ON adr_adresses_80 USING gist (geometrie);
CREATE INDEX adr_adresses_81_voi_id_numero_rep ON adr_adresses_81 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_81_geometrie ON adr_adresses_81 USING gist (geometrie);
CREATE INDEX adr_adresses_82_voi_id_numero_rep ON adr_adresses_82 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_82_geometrie ON adr_adresses_82 USING gist (geometrie);
CREATE INDEX adr_adresses_83_voi_id_numero_rep ON adr_adresses_83 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_83_geometrie ON adr_adresses_83 USING gist (geometrie);
CREATE INDEX adr_adresses_84_voi_id_numero_rep ON adr_adresses_84 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_84_geometrie ON adr_adresses_84 USING gist (geometrie);
CREATE INDEX adr_adresses_85_voi_id_numero_rep ON adr_adresses_85 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_85_geometrie ON adr_adresses_85 USING gist (geometrie);
CREATE INDEX adr_adresses_86_voi_id_numero_rep ON adr_adresses_86 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_86_geometrie ON adr_adresses_86 USING gist (geometrie);
CREATE INDEX adr_adresses_87_voi_id_numero_rep ON adr_adresses_87 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_87_geometrie ON adr_adresses_87 USING gist (geometrie);
CREATE INDEX adr_adresses_88_voi_id_numero_rep ON adr_adresses_88 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_88_geometrie ON adr_adresses_88 USING gist (geometrie);
CREATE INDEX adr_adresses_89_voi_id_numero_rep ON adr_adresses_89 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_89_geometrie ON adr_adresses_89 USING gist (geometrie);
CREATE INDEX adr_adresses_90_voi_id_numero_rep ON adr_adresses_90 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_90_geometrie ON adr_adresses_90 USING gist (geometrie);
CREATE INDEX adr_adresses_91_voi_id_numero_rep ON adr_adresses_91 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_91_geometrie ON adr_adresses_91 USING gist (geometrie);
CREATE INDEX adr_adresses_92_voi_id_numero_rep ON adr_adresses_92 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_92_geometrie ON adr_adresses_92 USING gist (geometrie);
CREATE INDEX adr_adresses_93_voi_id_numero_rep ON adr_adresses_93 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_93_geometrie ON adr_adresses_93 USING gist (geometrie);
CREATE INDEX adr_adresses_94_voi_id_numero_rep ON adr_adresses_94 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_94_geometrie ON adr_adresses_94 USING gist (geometrie);
CREATE INDEX adr_adresses_95_voi_id_numero_rep ON adr_adresses_95 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_95_geometrie ON adr_adresses_95 USING gist (geometrie);
CREATE INDEX adr_adresses_96_voi_id_numero_rep ON adr_adresses_96 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_96_geometrie ON adr_adresses_96 USING gist (geometrie);


-----------------------------------------------------------------------------------------------------------------
-- Section correspondant a la Corse et aux DOM et TOM
-----------------------------------------------------------------------------------------------------------------
CREATE INDEX adr_adresses_20_a_voi_id_numero_rep ON adr_adresses_20_a USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_20_a_geometrie ON adr_adresses_20_a USING gist (geometrie);
CREATE INDEX adr_adresses_20_b_voi_id_numero_rep ON adr_adresses_20_b USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_20_b_geometrie ON adr_adresses_20_b USING gist (geometrie);

CREATE INDEX adr_adresses_971_voi_id_numero_rep ON adr_adresses_971 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_971_geometrie ON adr_adresses_971 USING gist (geometrie);
CREATE INDEX adr_adresses_972_voi_id_numero_rep ON adr_adresses_972 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_972_geometrie ON adr_adresses_972 USING gist (geometrie);
CREATE INDEX adr_adresses_973_voi_id_numero_rep ON adr_adresses_973 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_973_geometrie ON adr_adresses_973 USING gist (geometrie);
CREATE INDEX adr_adresses_974_voi_id_numero_rep ON adr_adresses_974 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_974_geometrie ON adr_adresses_974 USING gist (geometrie);
CREATE INDEX adr_adresses_975_voi_id_numero_rep ON adr_adresses_975 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_975_geometrie ON adr_adresses_975 USING gist (geometrie);
CREATE INDEX adr_adresses_976_voi_id_numero_rep ON adr_adresses_976 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_976_geometrie ON adr_adresses_976 USING gist (geometrie);
CREATE INDEX adr_adresses_984_voi_id_numero_rep ON adr_adresses_984 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_984_geometrie ON adr_adresses_984 USING gist (geometrie);
CREATE INDEX adr_adresses_986_voi_id_numero_rep ON adr_adresses_986 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_986_geometrie ON adr_adresses_986 USING gist (geometrie);
CREATE INDEX adr_adresses_987_voi_id_numero_rep ON adr_adresses_987 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_987_geometrie ON adr_adresses_987 USING gist (geometrie);
CREATE INDEX adr_adresses_988_voi_id_numero_rep ON adr_adresses_988 USING btree (voi_id, adr_numero,adr_rep);
CREATE INDEX adr_adresses_988_geometrie ON adr_adresses_988 USING gist (geometrie);
